-- Commercial foundation: permanent accounts, protected economy, memories,
-- anniversaries, check-ins, audit logs and membership entitlements.

create table if not exists public.menu_catalog (
  id text primary key,
  category text not null check (category in ('food','care','date','limited')),
  name text not null,
  price integer not null check (price > 0),
  image_url text,
  is_limited boolean not null default false,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.menu_catalog(id, category, name, price, image_url, is_limited) values
  ('fruit-tea','food','缤纷水果茶',28,'/assets/menu/fruit-tea.png',false),
  ('ice-cream','food','草莓冰淇淋',32,'/assets/menu/ice-cream.png',false),
  ('milk-tea','food','奶茶投喂',36,'/assets/menu/milk-tea.png',false),
  ('duck-neck','food','绝味鸭脖',38,'/assets/menu/duck-neck.png',false),
  ('breakfast','food','爱心早餐',42,'/assets/menu/breakfast.png',false),
  ('fried-chicken','food','炸鸡可乐',48,'/assets/menu/fried-chicken.png',false),
  ('cake','food','草莓奶油蛋糕',52,'/assets/menu/cake.png',false),
  ('sushi','food','寿司约会',56,'/assets/menu/sushi.png',false),
  ('roast-chicken','food','香喷喷烤鸡',62,'/assets/menu/roast-chicken.png',false),
  ('hotpot','food','暖呼呼火锅',68,'/assets/menu/hotpot.png',false),
  ('crayfish','food','麻辣小龙虾',72,'/assets/menu/crayfish.png',false),
  ('bbq','food','快乐烤肉',78,'/assets/menu/bbq.png',false),
  ('hug','care','十分钟抱抱',48,null,false),
  ('wake-up','care','温柔叫早',56,null,false),
  ('dry-hair','care','帮忙吹头发',62,null,false),
  ('sleep','care','晚安哄睡',68,null,false),
  ('no-phone','care','一小时不看手机',78,null,false),
  ('massage','care','肩颈按摩',88,null,false),
  ('listen','care','认真倾听一小时',98,null,false),
  ('hair-wash','care','豪华洗头服务',118,null,false),
  ('walk','date','牵手散步',60,null,false),
  ('sunset','date','去看日落',78,null,false),
  ('movie','date','电影之夜',88,null,false),
  ('cook','date','一起做顿饭',98,null,false),
  ('coffee','date','咖啡店约会',108,null,false),
  ('museum','date','逛展览馆',118,null,false),
  ('picnic','date','公园野餐',138,null,false),
  ('day-trip','date','周末小旅行',188,null,false),
  ('choose-meal','limited','今天吃什么我决定',120,null,true),
  ('forgive','limited','和好抱抱券',148,null,true),
  ('wish','limited','任性愿望券',188,null,true),
  ('full-day','limited','一整天听你安排',228,null,true),
  ('anniversary','limited','纪念日惊喜',288,null,true),
  ('staycation','limited','双人度假日',360,null,true)
on conflict (id) do update set
  category = excluded.category,
  name = excluded.name,
  price = excluded.price,
  image_url = excluded.image_url,
  is_limited = excluded.is_limited,
  updated_at = now();

create table if not exists public.action_rate_limits (
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  window_started_at timestamptz not null,
  hits integer not null default 1,
  primary key (user_id, action, window_started_at)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  couple_id uuid references public.couples(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.memory_entries (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  caption text not null check (char_length(caption) between 1 and 160),
  happened_on date not null default current_date,
  image_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.anniversaries (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 40),
  event_date date not null,
  repeats_yearly boolean not null default true,
  reminder_days integer not null default 3 check (reminder_days between 0 and 30),
  created_at timestamptz not null default now()
);

create table if not exists public.daily_checkins (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  checked_on date not null default current_date,
  reward integer not null default 1 check (reward between 0 and 3),
  created_at timestamptz not null default now(),
  unique(user_id, checked_on)
);

create table if not exists public.membership_plans (
  id text primary key,
  name text not null,
  monthly_price_cents integer not null default 0 check (monthly_price_cents >= 0),
  features jsonb not null default '[]'::jsonb,
  is_active boolean not null default true
);

insert into public.membership_plans(id, name, monthly_price_cents, features) values
  ('free','基础版',0,'["双人同步","任务与甜心币","回忆与纪念日","数据导出"]'::jsonb),
  ('plus','甜心会员',1200,'["更多照片空间","高级主题","纪念日提前提醒","专属统计"]'::jsonb)
on conflict (id) do update set name = excluded.name, monthly_price_cents = excluded.monthly_price_cents, features = excluded.features;

create table if not exists public.memberships (
  couple_id uuid primary key references public.couples(id) on delete cascade,
  plan_id text not null default 'free' references public.membership_plans(id),
  status text not null default 'active' check (status in ('active','past_due','canceled','trialing')),
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.memberships(couple_id, plan_id)
select id, 'free' from public.couples
on conflict (couple_id) do nothing;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'support' check (role in ('support','operator','owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.app_errors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  couple_id uuid references public.couples(id) on delete cascade,
  message text not null,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.menu_catalog enable row level security;
alter table public.action_rate_limits enable row level security;
alter table public.audit_logs enable row level security;
alter table public.memory_entries enable row level security;
alter table public.anniversaries enable row level security;
alter table public.daily_checkins enable row level security;
alter table public.membership_plans enable row level security;
alter table public.memberships enable row level security;
alter table public.admin_users enable row level security;
alter table public.app_errors enable row level security;

drop policy if exists "read active menu" on public.menu_catalog;
create policy "read active menu" on public.menu_catalog for select using (is_active);
drop policy if exists "read own audit log" on public.audit_logs;
create policy "read own audit log" on public.audit_logs for select using (
  user_id = auth.uid() or exists (
    select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = audit_logs.couple_id
  )
);
drop policy if exists "read couple memories" on public.memory_entries;
create policy "read couple memories" on public.memory_entries for select using (
  exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = memory_entries.couple_id)
);
drop policy if exists "create couple memories" on public.memory_entries;
create policy "create couple memories" on public.memory_entries for insert with check (
  created_by = auth.uid() and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = memory_entries.couple_id)
);
drop policy if exists "delete own memories" on public.memory_entries;
create policy "delete own memories" on public.memory_entries for delete using (created_by = auth.uid());
drop policy if exists "manage couple anniversaries" on public.anniversaries;
create policy "manage couple anniversaries" on public.anniversaries for all using (
  exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = anniversaries.couple_id)
) with check (
  created_by = auth.uid() and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = anniversaries.couple_id)
);
drop policy if exists "read couple checkins" on public.daily_checkins;
create policy "read couple checkins" on public.daily_checkins for select using (
  exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = daily_checkins.couple_id)
);
drop policy if exists "read membership plans" on public.membership_plans;
create policy "read membership plans" on public.membership_plans for select using (is_active);
drop policy if exists "read couple membership" on public.memberships;
create policy "read couple membership" on public.memberships for select using (
  exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id = memberships.couple_id)
);
drop policy if exists "read own admin role" on public.admin_users;
create policy "read own admin role" on public.admin_users for select using (user_id = auth.uid());
drop policy if exists "admins read app errors" on public.app_errors;
create policy "admins read app errors" on public.app_errors for select using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid() and a.role in ('operator','owner'))
);

create or replace function public.assert_action_limit(p_action text, p_max_hits integer, p_window_minutes integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window timestamptz;
  v_hits integer;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if p_max_hits < 1 or p_window_minutes < 1 then raise exception 'invalid rate limit'; end if;
  v_window := to_timestamp(floor(extract(epoch from now()) / (p_window_minutes * 60)) * (p_window_minutes * 60));
  insert into public.action_rate_limits(user_id, action, window_started_at, hits)
  values (auth.uid(), p_action, v_window, 1)
  on conflict (user_id, action, window_started_at)
  do update set hits = action_rate_limits.hits + 1
  returning hits into v_hits;
  if v_hits > p_max_hits then raise exception 'rate limit exceeded'; end if;
end;
$$;

create or replace function public.write_audit(p_couple_id uuid, p_action text, p_metadata jsonb default '{}'::jsonb)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.audit_logs(couple_id, user_id, action, metadata)
  values (p_couple_id, auth.uid(), p_action, coalesce(p_metadata, '{}'::jsonb));
$$;

create or replace function public.place_couple_order(
  p_id uuid,
  p_item_id text,
  p_item_name text,
  p_image_url text,
  p_price integer,
  p_note text,
  p_desired_time text,
  p_from_name text,
  p_to_name text
)
returns table(order_id uuid, coin_balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
  v_balance integer;
  v_item public.menu_catalog%rowtype;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  perform public.assert_action_limit('place_order', 12, 10);
  select couple_id into v_couple_id from public.profiles where user_id = auth.uid();
  if v_couple_id is null then raise exception 'not paired'; end if;
  select * into v_item from public.menu_catalog where id = p_item_id and is_active;
  if v_item.id is null then raise exception 'invalid item'; end if;
  if char_length(coalesce(p_note, '')) > 160 or char_length(coalesce(p_desired_time, '')) > 40 then raise exception 'invalid order details'; end if;
  if char_length(trim(coalesce(p_from_name, ''))) not between 1 and 20 or char_length(trim(coalesce(p_to_name, ''))) not between 1 and 20 then raise exception 'invalid names'; end if;
  if v_item.is_limited and exists (
    select 1 from public.orders where couple_id = v_couple_id and item_id = v_item.id and status <> 'rejected'
  ) then raise exception 'limited item already used'; end if;

  update public.couples set coin_balance = couples.coin_balance - v_item.price
  where id = v_couple_id and couples.coin_balance >= v_item.price
  returning couples.coin_balance into v_balance;
  if v_balance is null then raise exception 'insufficient balance'; end if;

  insert into public.orders(id, couple_id, created_by, item_id, item_name, image_url, price, note, desired_time, status, from_name, to_name)
  values (p_id, v_couple_id, auth.uid(), v_item.id, v_item.name, v_item.image_url, v_item.price, trim(coalesce(p_note, '')), p_desired_time, 'pending', trim(p_from_name), trim(p_to_name));
  perform public.write_audit(v_couple_id, 'order.created', jsonb_build_object('order_id', p_id, 'item_id', v_item.id, 'price', v_item.price));
  return query select p_id, v_balance;
end;
$$;

create or replace function public.claim_couple_task(p_task_id text)
returns table(coin_balance integer, claim_key text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
  v_frequency text;
  v_reward integer;
  v_period_key text;
  v_balance integer;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  perform public.assert_action_limit('claim_task', 16, 10);
  select couple_id into v_couple_id from public.profiles where user_id = auth.uid();
  if v_couple_id is null then raise exception 'not paired'; end if;
  select frequency, reward into v_frequency, v_reward from public.task_catalog where id = p_task_id;
  if v_reward is null then raise exception 'invalid task'; end if;
  v_period_key := case when v_frequency = 'daily' then current_date::text else date_trunc('week', current_date)::date::text end;
  insert into public.task_claims(couple_id, user_id, task_id, period_key, reward)
  values (v_couple_id, auth.uid(), p_task_id, v_period_key, v_reward);
  update public.couples set coin_balance = couples.coin_balance + v_reward where id = v_couple_id returning couples.coin_balance into v_balance;
  perform public.write_audit(v_couple_id, 'task.claimed', jsonb_build_object('task_id', p_task_id, 'reward', v_reward, 'period', v_period_key));
  return query select v_balance, v_period_key;
end;
$$;

create or replace function public.daily_checkin()
returns table(coin_balance integer, streak integer, checked_on date, reward integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
  v_balance integer;
  v_streak integer := 0;
  v_day date := current_date;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  perform public.assert_action_limit('daily_checkin', 4, 60);
  select couple_id into v_couple_id from public.profiles where user_id = auth.uid();
  if v_couple_id is null then raise exception 'not paired'; end if;
  insert into public.daily_checkins(couple_id, user_id, checked_on, reward) values (v_couple_id, auth.uid(), current_date, 1);
  update public.couples set coin_balance = couples.coin_balance + 1 where id = v_couple_id returning couples.coin_balance into v_balance;
  while exists (select 1 from public.daily_checkins where user_id = auth.uid() and checked_on = v_day) loop
    v_streak := v_streak + 1;
    v_day := v_day - 1;
  end loop;
  perform public.write_audit(v_couple_id, 'checkin.created', jsonb_build_object('streak', v_streak, 'reward', 1));
  return query select v_balance, v_streak, current_date, 1;
end;
$$;

create or replace function public.get_checkin_status()
returns table(streak integer, checked_today boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_streak integer := 0;
  v_day date := current_date;
begin
  while exists (select 1 from public.daily_checkins where user_id = auth.uid() and checked_on = v_day) loop
    v_streak := v_streak + 1;
    v_day := v_day - 1;
  end loop;
  return query select v_streak, exists(select 1 from public.daily_checkins where user_id = auth.uid() and checked_on = current_date);
end;
$$;

create or replace function public.update_order_status(p_order_id uuid, p_status text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
begin
  if p_status not in ('accepted','doing','done','rejected') then raise exception 'invalid status'; end if;
  perform public.assert_action_limit('update_order', 30, 10);
  select o.* into v_order from public.orders o join public.profiles p on p.couple_id = o.couple_id
  where o.id = p_order_id and p.user_id = auth.uid();
  if v_order.id is null then raise exception 'order not found'; end if;
  if not ((v_order.status = 'pending' and p_status in ('accepted','rejected')) or (v_order.status = 'accepted' and p_status = 'doing') or (v_order.status = 'doing' and p_status = 'done')) then
    raise exception 'invalid transition';
  end if;
  update public.orders set status = p_status where id = p_order_id;
  perform public.write_audit(v_order.couple_id, 'order.status_changed', jsonb_build_object('order_id', p_order_id, 'from', v_order.status, 'to', p_status));
  return p_status;
end;
$$;

create or replace function public.leave_couple_space()
returns table(remaining_members integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
  v_remaining integer;
begin
  select couple_id into v_couple_id from public.profiles where user_id = auth.uid();
  if v_couple_id is null then raise exception 'not paired'; end if;
  perform public.write_audit(v_couple_id, 'couple.left', '{}'::jsonb);
  delete from public.push_subscriptions where user_id = auth.uid();
  delete from public.profiles where user_id = auth.uid();
  select count(*)::integer into v_remaining from public.profiles where couple_id = v_couple_id;
  if v_remaining = 0 then delete from public.couples where id = v_couple_id; end if;
  return query select v_remaining;
end;
$$;

create or replace function public.delete_my_account()
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_couple_id uuid;
begin
  if v_user_id is null then raise exception 'not authenticated'; end if;
  select couple_id into v_couple_id from public.profiles where user_id = v_user_id;
  if v_couple_id is not null then
    perform public.write_audit(v_couple_id, 'account.deleted', '{}'::jsonb);
    delete from public.push_subscriptions where user_id = v_user_id;
    delete from public.profiles where user_id = v_user_id;
    if not exists (select 1 from public.profiles where couple_id = v_couple_id) then delete from public.couples where id = v_couple_id; end if;
  end if;
  delete from auth.users where id = v_user_id;
  return true;
end;
$$;

create or replace function public.record_client_error(p_message text, p_context jsonb default '{}'::jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
begin
  if auth.uid() is null then return; end if;
  perform public.assert_action_limit('client_error', 10, 60);
  if char_length(coalesce(p_message, '')) > 500 or octet_length(coalesce(p_context, '{}'::jsonb)::text) > 4000 then return; end if;
  select couple_id into v_couple_id from public.profiles where user_id = auth.uid();
  insert into public.app_errors(user_id, couple_id, message, context)
  values (auth.uid(), v_couple_id, coalesce(nullif(trim(p_message), ''), 'unknown client error'), coalesce(p_context, '{}'::jsonb));
end;
$$;

create or replace function public.admin_dashboard_metrics()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not exists (select 1 from public.admin_users where user_id = auth.uid() and role in ('operator','owner')) then raise exception 'admin required'; end if;
  return jsonb_build_object(
    'users', (select count(*) from auth.users),
    'couples', (select count(*) from public.couples),
    'orders_24h', (select count(*) from public.orders where created_at >= now() - interval '24 hours'),
    'errors_24h', (select count(*) from public.app_errors where created_at >= now() - interval '24 hours'),
    'generated_at', now()
  );
end;
$$;

create or replace function public.create_couple_space(display_name text)
returns table(couple_id uuid, invite_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
  v_invite_code text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then raise exception 'permanent account required'; end if;
  perform public.assert_action_limit('create_space', 3, 60);
  if exists (select 1 from public.profiles where user_id = auth.uid()) then raise exception 'already paired'; end if;
  loop
    v_invite_code := lpad((floor(random() * 900000) + 100000)::text, 6, '0');
    begin
      insert into public.couples(invite_code) values (v_invite_code) returning id into v_couple_id;
      exit;
    exception when unique_violation then null;
    end;
  end loop;
  insert into public.profiles(user_id, couple_id, display_name) values (auth.uid(), v_couple_id, display_name);
  insert into public.memberships(couple_id, plan_id) values (v_couple_id, 'free') on conflict do nothing;
  perform public.write_audit(v_couple_id, 'couple.created', jsonb_build_object('identity', display_name));
  return query select v_couple_id, v_invite_code;
end;
$$;

create or replace function public.join_couple_space(code text, display_name text)
returns table(couple_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then raise exception 'permanent account required'; end if;
  perform public.assert_action_limit('join_space', 10, 60);
  if exists (select 1 from public.profiles where user_id = auth.uid()) then raise exception 'already paired'; end if;
  select id into v_couple_id from public.couples where invite_code = trim(code);
  if v_couple_id is null then raise exception 'invalid invite code'; end if;
  if (select count(*) from public.profiles where couple_id = v_couple_id) >= 2 then raise exception 'couple space is full'; end if;
  insert into public.profiles(user_id, couple_id, display_name) values (auth.uid(), v_couple_id, display_name);
  insert into public.memberships(couple_id, plan_id) values (v_couple_id, 'free') on conflict do nothing;
  perform public.write_audit(v_couple_id, 'couple.joined', jsonb_build_object('identity', display_name));
  return query select v_couple_id;
end;
$$;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('memory-photos', 'memory-photos', false, 8388608, array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "couple memory photo read" on storage.objects;
create policy "couple memory photo read" on storage.objects for select using (
  bucket_id = 'memory-photos' and exists (
    select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id::text = (storage.foldername(name))[1]
  )
);
drop policy if exists "couple memory photo upload" on storage.objects;
create policy "couple memory photo upload" on storage.objects for insert with check (
  bucket_id = 'memory-photos' and exists (
    select 1 from public.profiles p where p.user_id = auth.uid() and p.couple_id::text = (storage.foldername(name))[1]
  )
);
drop policy if exists "own memory photo delete" on storage.objects;
create policy "own memory photo delete" on storage.objects for delete using (bucket_id = 'memory-photos' and owner_id = auth.uid()::text);

grant select on public.menu_catalog, public.membership_plans to anon, authenticated;
grant select on public.audit_logs, public.memory_entries, public.anniversaries, public.daily_checkins, public.memberships, public.admin_users to authenticated;
grant insert, delete on public.memory_entries to authenticated;
grant insert, update, delete on public.anniversaries to authenticated;
grant execute on function public.assert_action_limit(text, integer, integer) to authenticated;
grant execute on function public.place_couple_order(uuid, text, text, text, integer, text, text, text, text) to authenticated;
grant execute on function public.claim_couple_task(text) to authenticated;
grant execute on function public.daily_checkin() to authenticated;
grant execute on function public.get_checkin_status() to authenticated;
grant execute on function public.update_order_status(uuid, text) to authenticated;
grant execute on function public.leave_couple_space() to authenticated;
grant execute on function public.delete_my_account() to authenticated;
grant execute on function public.create_couple_space(text) to authenticated;
grant execute on function public.join_couple_space(text, text) to authenticated;
grant execute on function public.record_client_error(text, jsonb) to authenticated;
grant execute on function public.admin_dashboard_metrics() to authenticated;
revoke execute on function public.write_audit(uuid, text, jsonb) from public, anon, authenticated;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'memory_entries') then
    alter publication supabase_realtime add table public.memory_entries;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'anniversaries') then
    alter publication supabase_realtime add table public.anniversaries;
  end if;
end
$$;
